<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginFormRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'email' => 'required|email',
            'password' => 'required',
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'email.required' => 'Email chưa nhập vào!',
            'password.required' => 'Password chưa được nhập vào!',
            'email.email' => 'Không đúng định dạng email!',
        ];
    }
}
